### ISSUE TITLE
[Feature Request] Introduce a user friendly way to describe schema of the data

### ISSUE THREAD

**Issue by Rubix982** [samadpls/Querypls#3]
As the title states, a way for the user to describe their schema once and then ask high level questions over it would be extremely useful.

Most databases and ORMs support ways where you can extract the DDL for your tables. I assume doing this and then pasting it as a pre-text before sending the text box question can have good enough results just for the naive case.

To test.

**Comment by samadpls** [comment]
Thank you for sharing your suggestion. We will work on this.🚀
